version: "3.9"
services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: smart-clinic
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
    environment:
      SPRING_PROFILES_ACTIVE: prod

  mysql:
    image: mysql:8.3.0
    container_name: cms-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cms
    ports:
      - "3307:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  mongodb:
    image: mongo:7.0.5
    container_name: cms-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: cms-prescriptions
    ports:
      - "27018:27017"
    volumes:
      - ./docker/mongo/data:/data/db