name: Lint Dockerfiles
on: [ push, pull_request ]

jobs:
  dockerlint:
    runs-on: ubuntu-latest
    name: Lint Dockerfiles
    steps:
      # 1. Checkout the repository
      - uses: actions/checkout@v3

      # 2. Run Hadolint on your Dockerfile
      - name: Run hadolint
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ./app/Dockerfile
